### ISSUE TITLE
Looking for longer term (year over year) storage of our Count Min Sketch data. 

### ISSUE THREAD

**Issue by sophiemorrigan** [RedisBloom/RedisBloom#157]
Ideally we'd be able to store our CMS objects into some file format, then parse them back out later (even years later). 

I can write the CMS objects to a rdb file, but it appears that dump format is bound to the version of redis that did the actual dump. 
https://redis.io/commands/dump
"An RDB version is encoded inside the serialized value, so that different Redis versions with incompatible RDB formats will refuse to process the serialized value."

I'd like to be able to convert them into a generic format so our long term data can be recalled in the future as redis upgrades it's versioning. Can be exported / converted into to some sort of generic JSON structure that could be scanned by a map reduce? 

Related Issue / question 
Bloom Filters seem to have a specialized scan dump and load chunk:
https://oss.redislabs.com/redisbloom/Bloom_Commands/#bfscandump
Are these dump and load formats for bloom filters considered stable across redis releases?

Thanks,
Sophie

**Comment by ashtul** [comment]
@sophiemorrigan 
I am more than intrigued to hear about your use case. Could you please share it with us.

In RedisBloom we make sure to have back support for older versions therefore, you should be able to load your data in the future. Regardless, the version depends on the module, not Redis itself (unless something major will unexpectedly change) and therefore you will be able to use a version of the module in case we break the backward support.

The scandump and loaddump of bloom and cuckoo are there because these data structures can get large enough and hit the 512MB limit of Redis rdb. I can't imagine a use of CMS which reaches this limit.

**Comment by sophiemorrigan** [comment]
We generate about 1 gb of CMS data per 24 hours (we cut them into 12 hour bins per

**Comment by sophiemorrigan** [comment]
I can't say the exact use case, but we generate about 1gb a day of Bloom / CMS objects in our redis.  With 50 CMS / bloom objects; each binned to 12 hours split over 25 different types. Was looking for a way to store the 1gb a day somewhere else we could ETL / query over, but from what I can find there is no way (other than restoring the dump binary file back into a redis instance)
