### ISSUE TITLE
Need a method to reduce bloom filter capacity

### ISSUE THREAD

**Issue by rvencu** [RedisBloom/RedisBloom#384]
At the start of the project, we estimated the number of 300 billion items. Therefore we prepared a 256GB RAM machine to hold the filter. We are now at about 80% progress, and due to high duplication, we think the total number of items would not be greater than 50 billion.

Therefore to save cloud expenses, we would like the flexibility to reduce the filter's capacity while retaining the valuable data.

It is ok for us to scan dump and maybe load only a limited number of chunks back into a  new bloom filter key. However, should a mechanism be able to change the dump headers, we would like to redefine the capacity (and error_rate if needed?) to a smaller value before restoring.

**Comment by ashtul** [comment]
@rvencu Thank you for the question.

It is not possible to reduce the size of the filter once it was created since the filter does not have the original data anymore which is required to recalculate the hash value.

RedisBloom offers a scalable bloom filter that allows you to start with a lower capacity and add more capacity if it is needed but it cannot reduce the size of the original filter if it was overestimated.

**Comment by rvencu** [comment]
Thanks. Learned something more... good to know the right strategy
