### ISSUE TITLE
Add a way of getting to the count / size / cardinality of the Bloom Filter directly

### ISSUE THREAD

**Issue by simonprickett** [RedisBloom/RedisBloom#389]
I can get information about how many items were inserted into the Bloom Filter from `BF.INFO` by parsing the result out:

```bash
127.0.0.1:6379> bf.madd somebloom the quick brown fox ran up the hill and did some stuff because it can
 1) (integer) 1
 2) (integer) 1
 3) (integer) 1
 4) (integer) 1
 5) (integer) 1
 6) (integer) 1
 7) (integer) 0
 8) (integer) 1
 9) (integer) 1
10) (integer) 1
11) (integer) 1
12) (integer) 1
13) (integer) 1
14) (integer) 1
15) (integer) 1
127.0.0.1:6379> bf.info somebloom
 1) Capacity
 2) (integer) 100
 3) Size
 4) (integer) 290
 5) Number of filters
 6) (integer) 1
 7) Number of items inserted
 8) (integer) 14
 9) Expansion rate
10) (integer) 2
```

I feel it would be useful to have a command that did something like this (equivalent to `PFCOUNT` for Hyperloglog):

```bash
127.0.0.1:6379> bf.count somebloom
(integer) 14
```

**Comment by LiorKogan** [comment]
Thank you @simonprickett 

Maybe we should add optional flags - for receiving a single value.
`BF.INFO {key} [CAPACITY|SIZE|FILTERS|ITEMS|ERATE]`

What do you think?

**Comment by simonprickett** [comment]
@LiorKogan yes that would make sense for me too.  Thanks for looking at this.

**Comment by MakDon** [comment]
Want this feature too.
Maybe it would be nice that `bf.count not:exist:key` returns `0` instead of an error `-ERR not found`

**Comment by MakDon** [comment]
Hi @LiorKogan , could we add an option here, with which `BF.INFO [CAPACITY|SIZE|FILTERS|ITEMS|EXPANSION]` return 0 instead of `-ERR not found`?  Otherwise, we have to check if the key exists before `BF.INFO`, which would waste a RTT and is not convenient for pipelining.
The scene has been in #488 in detail.
```
127.0.0.1:6379> BF.INFO key:not:exist
-ERR not found
127.0.0.1:6379> BF.INFO key:not:exist NC
 1) (integer) 0
```
Thanks very much.

**Comment by LiorKogan** [comment]
@MakDon this goes against Redis philosophy.
Commands that receive a key should error when the key doesn't exist or of the wrong data type.

**Comment by MakDon** [comment]
> @MakDon this goes against Redis philosophy. Commands that receive a key should error when the key doesn't exist or of the wrong data type.

Maybe it is worth discussing. In many redis commands, they return 0 when the key doesn't exist. For example:
- [LLEN](https://redis.io/commands/llen/): 
```
redis> LLEN NOTEXIST
(integer) 0
```
- [SCARD](https://redis.io/commands/scard/): Integer reply: the cardinality (number of elements) of the set, or 0 if key does not exist.
```
redis> SCARD NOTEXIST
(integer) 0
```
- [HLEN](https://redis.io/commands/hlen/): Integer reply: number of fields in the hash, or 0 when key does not exist.
```
redis> HLEN NOTEXIST
(integer) 0
```
- [ZCARD](https://redis.io/commands/zcard/):  Integer reply: the cardinality (number of elements) of the sorted set, or 0 if key does not exist.
```
redis> ZCARD notexist
(integer) 0
```

**Comment by simonprickett** [comment]
Returning an error when the key doesn't exist does not go against the "Redis philosophy" it's what people expect and often makes for easier coding.  For example `DEL <somekey>` doesn't error when they key doesn't exist, but `FT.DROPINDEX` returns an error response which requires unnecessary code to handle and isn't good developer experience.  I'm with @MakDon here.

**Comment by LiorKogan** [comment]
@MakDon @simonprickett 
You are correct about Redis's philosophy, I was wrong.

So the suggested syntax is `BF.INFO key [CAPACITY | SIZE | FILTERS | ITEMS | EXPANSION] [NX]`

and the behavior is:

- If `key` is a Bloom Filter: return information about the key
- If `key` is of another type: return an error
- If `key` does not exist: return an error when `NX` is not specified or 0 when `NX` is specified

I'm for it.
Would it be better to return -1 instead of 0?

@gkorland, @itamarhaber @ashtul, @leibale - second opinion?

**Comment by leibale** [comment]
@LiorKogan
1.  In other places `NX` means "execute the command only if the key does not exist" - for example, `SET key value NX` will set `key` to `value` only if `key` is empty - using it to do something else will be confusing..
2. Unlike hash and list, an empty bloom filter and empty key are not the same - you need to `BF.RESERVE` a bloom filter before using it.
```
> HSET key field value
(integer) 1
> TYPE key
"hash"
> HDEL key field
(integer) 1
> TYPE key
"none"
```
3. I prefer `BF.COUNT key` over `BF.INFO key SIZE`, and it should return:
3.1 `-1` if the key does not exist.
3.2 `integer` if the key is a bloom filter
3.3 `error` otherwise

**Comment by itamarhaber** [comment]
I like philosophical discussions. IMHO, the way to go about this is to add `BF.CARD` (as BF implements a subset of the operations defined for the Set ADT). It should return `-WRONGTYPE` or greater-or-equal-to zero integers. Non-existing keys should be treated as empty.

I agree w/ @leibale here, although you can `BF.ADD` w/o `BF.RESERVE` (and use the defaults).

WRT `NX`: the modifier exists only in write commands, whereas this is read-only. It simply doesn't belong here.

WRT 0 replies: because Redis deletes most nested core data structures when they're empty, simple counts (e.g., `LLEN`, `SCARD`) are 0 for non-existing keys (i.e. empty == non-existing).
However, BF et al behave more like streams in sense of having their own metadata and existing w/o data (e.g. `XGROUP ... MKSTREAM` and `BF.RESERVE`).
Note that when you do `XINFO STREAM no:such:stream` you actually do get a "-ERR no such key", which makes sense.

WRT to -1 replies: that's a very clever trick that I'm very much against. AFAIR, only `TTL` does that and more (or less, because it can return -2), and that's confusing.

WRT optional flags: changing the reply's structure according to arguments is bad practice. Returning an array of tuples (i.e., a RESP3 map) or an integer is a sin that is likely to cause client authors to unite and revolt (see above ;)).

**Comment by simonprickett** [comment]
`BF.CARD` sounds like a good idea to me.

**Comment by LiorKogan** [comment]
Very well, thank you all. A new command then.

Suggested syntax:

---

`BF.CARD key`

Return the number of items that were added to this Bloom filter and detected as unique (items that caused at least one bit to be set in at least one sub-filter).

Return `0` if `key` does not exist.

Error when `key` is of a type other than Bloom filter.

---

@MakDon please confirm that this is aligned with your request (and I guess this is what you asked for in #488 5 months ago...)

**Comment by MakDon** [comment]
> @MakDon please confirm that this is aligned with your request (and I guess this is what you asked for in #488 5 months ago...)

Yes, this is what I proposed in #488 . And it was implemented in #489 
If the proposal is accepted, I am very glad to re-open, rebase and test the previous PR.
Thanks again. :D

**Comment by LiorKogan** [comment]
@MakDon 
Yes, please do so.
Thank you!

**Comment by MakDon** [comment]
Since #604 has been merged, it seems that we can close this issue now.
