### ISSUE TITLE
CF used huge memory

### ISSUE THREAD

**Issue by macrouss** [RedisBloom/RedisBloom#533]
In our application, we used cf for filter.
We created two cf. One has 92238 items, and another has 275937 items.
However, 92,238 items' CF used 8589918552 bytes (8 GB), and 275,937 items' CF only used 67092712 bytes (67MB).
The following info are the two CFs info.

############################
 CF.INFO  c22
 1) Size
 2) (integer) 67092712
 3) Number of buckets
 4) (integer) 8192
 5) Number of filters
 6) (integer) 12
 7) Number of items inserted
 8) (integer) 275929
 9) Number of items deleted
10) (integer) 161
11) Bucket size
12) (integer) 2
13) Expansion rate
14) (integer) 2
15) Max iterations
16) (integer) 20
#############################

 CF.INFO c15
 1) Size
 2) (integer) 8589918552
 3) Number of buckets
 4) (integer) 8192
 5) Number of filters
 6) (integer) 19
 7) Number of items inserted
 8) (integer) 92238
 9) Number of items deleted
10) (integer) 3
11) Bucket size
12) (integer) 2
13) Expansion rate
14) (integer) 2
15) Max iterations
16) (integer) 20

#############################

Why did the less itmes' CF use more memory?
Inserted items data form like "oCyqs56nKBfZ_ad4Ye85XjsSeqrg".

**Comment by ashtul** [comment]
@macrouss the first filter has 19 sub filters vs 12.  Each filter is twice as large as the previous one, so you can see how the memory would get that high. 
The reason is high number of duplicate of a certain element which fills all available buckets and triggers the creation of an additional filter. 
I see you deleted a few element, so I assume you need deletions. 

Try BUCKETSIZE=4 or even 8. 
Also note, the error rate increases as you add more filters and when you change bucketsize. Can you control the number of duplicates?

**Comment by macrouss** [comment]
Thanks for your help.
I have reduced repetition rate of data, then solved the problem.
If there be a new command of cf that can check duplicates before inserting, will be better solution.

**Comment by ashtul** [comment]
You can use `CF.ADDNX`, which does exactly what you describe.

**Comment by macrouss** [comment]
> 

If I use ADDNX, that will cause another problem, deleting elements can introduce false negative error rate.
In my program processing, false negative can not be accept, that will cause business vulnerabilities.
