### ISSUE TITLE
Bloom filter error rate is inaccurate

### ISSUE THREAD

**Issue by llh12345** [RedisBloom/RedisBloom#717]
I used bf.reserve to create a bloom filter and found that the error rate was half the error rate I specified. When the capacity of the Bloom filter is large, memory consumption will increase due to the above reasons.

![image](https://github.com/RedisBloom/RedisBloom/assets/43738754/69bde926-f732-4d7b-9e78-989acf862b00)

**Comment by llh12345** [comment]
I think the real error rate of the bloom filter actually created is the product of the user input error rate and ERROR_TIGHTENING_RATIO

![image](https://github.com/RedisBloom/RedisBloom/assets/43738754/6de824a3-dbce-4b6a-87ea-99b44ec794b8)

**Comment by LiorKogan** [comment]
See explanation of why it is so: https://github.com/RedisBloom/RedisBloom/issues/716#issuecomment-1870198481

@llh12345 to claim that `ERROR_TIGHTENING_RATIO` can be increased while maintaining the desired probability for false positives (`error_rate` argument of `BF.RESERVE`) you will have to prove it (either theoretically or empirically).

**Comment by ashtul** [comment]
@llh12345 the reason you see half the error rate is due to the fact RedisBloom is a `Scalable Bloom Filter`. In order to allow the filter to grow in size without compromising the error rate, it is initilized with half the error rate specified.
If you don't expect your filter to grow you can use `NONSCALING` when you call `BF.RESERVE`.
You can read more about it [here](https://gsd.di.uminho.pt/members/cbm/ps/dbloom.pdf).
